language: python
dist: trusty
sudo: required

stages:
  - name: build
  - name: deploy
    if: tag =~ v.*

python:
  - "3.4"

env:
  - CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0

install:
  - . .travis.setup

script:
  - python3 setup.py bdist_wheel
  - auditwheel repair -w dist dist/*

jobs:
  include:
    - stage: build
      after_script: skip
    - stage: deploy
      after_script:
        - twine upload dist/*manylinux* -u $PYPI_LOGIN -p $PYPI_PASS


notifications:
  email: false
