dist: trusty
sudo: required


matrix:
  include:
    - language: cpp
      install:
        - source .travis.install
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..
      script: skip
notifications:
  email: false