dist: trusty
sudo: required


matrix:
  include:
    - language: python
      python:
        - 3.4
        - 3.5
        - 3.6
      env:
        - CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0
      install: . .python.install
      deploy:
        provider: script
        script:
          - python3 setup.py bdist_wheel
          - auditwheel repair -w dist dist/*
          - twine upload dist/*manylinux* -u $PYPI_LOGIN -p $PYPI_PASS
        skip_cleanup: true
        on:
          tags: true

    - language: cpp
      install:
        - . .travis.install
        - mkdir build
        - cd build
        - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..

notifications:
  email: false